
<html>    
    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src ="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    </head>
    <style>
        .col-md-4{
            margin-left: 450px;
        }

        .row{
            width:100%;
        }
    </style>
    <div class="row">
        <div class="col-sm-6 col-md-4">
            <?php for ($i = 0; $i < count($this->threads); $i++) {
                ?>

                <div class="thumbnail">
                    <div class="caption">
                        <h3><a href="<?php echo $this->baseUrl() . '/thread/display/id/' . $this->threads[$i]['id'] ?>" ><?php echo $this->threads[$i]['title'] ?></a></h3>
                        <p><?php echo substr($this->threads[$i]['body'], 0, 15) . "..."; ?></p>
                    </div>
                    <p><a href="<?php echo $this->baseUrl() . '/thread/edit/id/' . $this->threads[$i]['id'] . '/toCategoryId/' . $this->toCategoryId; ?>" class="btn btn-primary" role="button">Edit</a> <a href="<?php echo $this->baseUrl() . '/thread/delete/id/' . $this->threads[$i]['id'] . '/toCategoryId/' . $this->toCategoryId; ?>" class="btn btn-danger" role="button">Delete</a></p>
                </div>
            <?php } ?>
        </div>
    </div>
</html>